name: Robot Framework Tests

on: push

jobs:
  test:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clonar arquivos do repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalação das Dependencias
      run: |
        pip install robotframework
        pip install robotframework-requests
        pip install Faker
        pip install robotframework-seleniumlibrary
        
    - name: Executando os testes de API do Robot
      run: |
        robot -d results/ tests/
      
    - name: Salvar resultado dos testes
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: robot-results
        path: ./results

 